name: Publish 

on:
  workflow_dispatch:
  push:
    branches:
     - main
    
# jobs
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/ckeckout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore
        run: dotnet restore ./src/eShopApp.Catalog/eShopApp.Catalog.sln
        
      - name: Build
        run: dotnet build ./src/eShopApp.Catalog/eShopApp.Catalog.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./src/eShopApp.Catalog/eShopApp.Catalog.sln --configuration Release --no-build
